config/routes.rb
Rails.application.routes.draw do
  #get 'pages/home'

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contactus' => 'pages#contactus'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My First Rails App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Home', root_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Contact Us', contactus_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>This is what I'm all 'bout. I'm working on my first Rails app!</p>

app/views/pages/contactus.html.erb
<h1>Contact us</h1>
<p>You can always find me on YouTube at <a target="_blank" href="https://www.youtube.com/channel/UCNwQRVsH2I-V8UZCBGiiJwQ?view_as=subscriber">Don't Panic UX</a> </p>

app/views/pages/home.html.erb
<!-- Ruby way of creating links; note these variables are created in config/routes -->

<!-- Typical HTML links replaced by above; how do you ensure syntax-ically correct HTML w/ ruby?
<a href="/">Home</a>
<a href="/about">About</a>
<a href="/contactus">Contact Us</a>
-->
<h1>Welcome to my website!</h1>
<p>Sign up here.</p>